apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: container-registry
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.242
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      targetPort: registry
