


echothings: ##Is a comment required?
	echo "hi"

##How do we handle the whole dependency thing again?

echo_with_deps: echobanana echoapple

echobanana:
	echo "banana"

echoapple:
	echo "apple"

clean:
	echo "I would've written 'rm -f *.o' in here"

ls:
	ls