apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-self
  namespace: monitoring
  labels:
    prometheus: homelab
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: web
