apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.220
spec:
  type: LoadBalancer
  selector:
    prometheus: prometheus #a service only selects pods in its own namespace, so its not a concern if you have another instance of prometheus in another namespace, neat
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web #comes from the container port name, so you can actually change the port name and still have it work, interesting
