apiVersion: v1
kind: Service
metadata:
  name: prometheus-example
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.243
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: example
  ports:
  - name: web
    port: 9090
    targetPort: web
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-example
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.244
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: example
  ports:
  - name: web
    port: 9093
    targetPort: web
