apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: chapter10-tempo
spec:
  selector:
    app: alloy
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: http
      port: 12345
      targetPort: http
