apiVersion: v1
kind: Service
metadata:
  name: my-lb
  namespace: nginx
spec:
#  clusterIP: 10.43.0.69
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80