# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.define "nextcloud" do |nextcloud|
    nextcloud.vm.box = "ubuntu/xenial64"
    nextcloud.vm.hostname = "nextcloud"
    nextcloud.vm.provision:shell, path: "files/server.sh"
    nextcloud.vm.network "public_network", bridge: "enp3s0", use_dhcp_assigned_default_route: true
  end
end
