apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
    - name: mypod
      image: mypod
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: app-secret-volume
          mountPath: /etc/app-secret
          readOnly: true
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret
