Vagrant.configure("2") do |config|

  config.vm.define "elk" do |elk|
    elk.vm.box = "debian/stretch64"
    elk.vm.hostname = "elk"
    elk.vm.provision:shell, path: "files/server.sh"
    elk.vm.network "public_network", bridge: "enp3s0", use_dhcp_assigned_default_route: true

  end
end